---
class: 4
flags: 0x0000
unid: OF437376CB33A18A32-ON0050FCF785257AA7
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.4
    signed: true
  - name: $FileNames
    type: text
    data: WEB-INF/faces-config.xml
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
    signed: true
  - name: $Revisions
    type: time
    data: "2012-10-30T10:44:36.46-04:00"
    dst: true
  - name: $TITLE
    type: text
    data: WEB-INF/faces-config.xml
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []