---
ACL:
  opaque: |
    Q0ECAE4CCwAAAAAABQAoABAAeACYAAEAAAAoAAQAAAAEBCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    tgAAACYCAAAAAAAACAIAAAAA4AAAAOABUgFyAQAAAAAAAEVBAwAAAAAAAAAAAAAABAYJAC1EZWZhdWx0
    LQAAAEVBAAAAAAAAAAAAAAAARxAUAFtPdGhlckRvbWFpblNlcnZlcnNdAOMKAUVBBgAAAAAAAAAAAAAA
    3gcUAFtMb2NhbERvbWFpblNlcnZlcnNdACoyAUVBBgAAAAAAAAAAAAAA/AcTAFtMb2NhbERvbWFpbkFk
    bWluc10AAABFQQMAAAAAAAAAAAAAACQGCwBbLURlZmF1bHQtXQAAAEVBAAAAAAAAAAAAAAAABRALAFtB
    bm9ueW1vdXNdAAAARUEEAAAAAAAAAAAAAAAABjMAW0NOPUxvdHVzIE5vdGVzIFRlbXBsYXRlIERldmVs
    b3BtZW50L089TG90dXMgTm90ZXNdAAAARUEGAAAAAAAAAAAAAAD4BxEATG9jYWxEb21haW5BZG1pbnMA
    ugFFQQYAAAAAAAAAAAAAANoHEgBMb2NhbERvbWFpblNlcnZlcnMAbQAARUEAAAAAAAAAAAAAAAAEEAkA
    QW5vbnltb3VzAAAARUEAAAAAAAAAAAAAAABGEBIAT3RoZXJEb21haW5TZXJ2ZXJzAFM=
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0